version: '3.3'

services:
  app:
      container_name: nest-jwt-auth-app 
      image: nest-jwt-auth-img
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      restart: always
